# Generated by Django 4.0.3 on 2022-04-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PT_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.cont_state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salary_Heads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('sec_no', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('editable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old')], max_length=20, null=True)),
                ('cate', models.CharField(blank=True, choices=[('Citizen', 'Citizen'), ('Senior Citizen', 'Senior Citizen'), ('Super Senior Citizen', 'Super Senior Citizen')], max_length=20, null=True)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('cdn_max', models.CharField(blank=True, choices=[('__gt__', '>'), ('__ge__', '>='), ('__lt__', '<'), ('__le__', '<='), ('__eq__', '==')], max_length=20, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax_slab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('rang_min', models.IntegerField(blank=True, null=True)),
                ('cdn_max', models.CharField(blank=True, choices=[('__gt__', '>'), ('__ge__', '>='), ('__lt__', '<'), ('__le__', '<='), ('__eq__', '==')], max_length=20, null=True)),
                ('rang_max', models.IntegerField(blank=True, null=True)),
                ('tax_rate', models.FloatField(blank=True, null=True)),
                ('slab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InTax.tax_header')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sec16_Dedu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('regime', models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old'), ('Both', 'Both')], max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('sec', models.CharField(blank=True, max_length=10, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ceil_limit', models.IntegerField(blank=True, null=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PT_Slab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('range_min', models.IntegerField(blank=True, null=True)),
                ('cdn_max', models.CharField(blank=True, choices=[('__gt__', '>'), ('__ge__', '>='), ('__lt__', '<'), ('__le__', '<='), ('__eq__', '==')], max_length=20, null=True)),
                ('range_max', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('slab', models.IntegerField(blank=True, null=True)),
                ('state', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='InTax.pt_header')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PF_Empr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('cate', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Handicapped', 'Handicapped'), ('International Worker', 'International Worker')], max_length=20, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('restricted', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('Basic', models.IntegerField(blank=True, null=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PF_Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('cate', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Handicapped', 'Handicapped'), ('International Worker', 'International Worker')], max_length=20, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('restricted', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('Basic', models.IntegerField(blank=True, null=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exemptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('regime', models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old'), ('Both', 'Both')], max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('sec', models.CharField(blank=True, max_length=10, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('ceil_pm', models.IntegerField(blank=True, null=True)),
                ('ceil_pa', models.IntegerField(blank=True, null=True)),
                ('hra_mc', models.FloatField(blank=True, null=True)),
                ('hra_nmc', models.FloatField(blank=True, null=True)),
                ('sal_per', models.FloatField(blank=True, null=True)),
                ('avg_hlfsal', models.FloatField(blank=True, null=True)),
                ('months', models.IntegerField(blank=True, null=True)),
                ('leave_division', models.FloatField(blank=True, null=True)),
                ('avg_monsal', models.IntegerField(blank=True, null=True)),
                ('commuted_pension', models.FloatField(blank=True, null=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
                ('ref_earn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InTax.salary_heads')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esi_Ratecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('empr_rate', models.FloatField(blank=True, null=True)),
                ('emp_rate', models.FloatField(blank=True, null=True)),
                ('block1_from', models.DateField(blank=True, null=True)),
                ('block1_to', models.DateField(blank=True, null=True)),
                ('block2_from', models.DateField(blank=True, null=True)),
                ('block2_to', models.DateField(blank=True, null=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chp_VIA_Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('regime', models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old'), ('Both', 'Both')], max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('sec', models.CharField(blank=True, max_length=10, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('ceili_pm', models.IntegerField(blank=True, null=True)),
                ('ceili_pa', models.IntegerField(blank=True, null=True)),
                ('deduct_mx', models.FloatField(blank=True, null=True)),
                ('sal_per', models.FloatField(blank=True, null=True)),
                ('excess_gti', models.FloatField(blank=True, null=True)),
                ('adj_gti', models.FloatField(blank=True, null=True)),
                ('norm_disab', models.IntegerField(blank=True, null=True)),
                ('severe_disab', models.IntegerField(blank=True, null=True)),
                ('citizen', models.IntegerField(blank=True, null=True)),
                ('sr_citizen', models.IntegerField(blank=True, null=True)),
                ('loan_sancfrm', models.DateField(blank=True, null=True)),
                ('loan_sancto', models.DateField(blank=True, null=True)),
                ('sdv_property', models.IntegerField(blank=True, null=True)),
                ('loan_amt', models.IntegerField(blank=True, null=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
