# Generated by Django 4.0.3 on 2022-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InTax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoriesAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_leave', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('Eligibility_for_leave', models.IntegerField(blank=True, null=True)),
                ('No_of_leaves_pa', models.IntegerField(blank=True, null=True)),
                ('Leave_Encashment_pm', models.FloatField(blank=True, null=True)),
                ('Carry_forword_Next_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_leave', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('Eligibility_for_leave', models.IntegerField(blank=True, null=True)),
                ('No_of_leaves_pa', models.IntegerField(blank=True, null=True)),
                ('Leave_Encashment_pm', models.FloatField(blank=True, null=True)),
                ('Carry_forword_Next_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
