# Generated by Django 4.0.3 on 2022-04-05 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=20, null=True, unique=True)),
                ('emp_name', models.JSONField(blank=True, default=dict, null=True)),
                ('emp_aadharname', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_name', models.JSONField(blank=True, default=dict, null=True)),
                ('gndr', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('perm_addr', models.JSONField(default=dict)),
                ('pres_addr', models.JSONField(default=dict)),
                ('loc', models.CharField(blank=True, max_length=20, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('probation', models.CharField(blank=True, max_length=10, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=10, null=True)),
                ('dor', models.DateField(blank=True, null=True)),
                ('resig_resns', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.JSONField(default=dict)),
                ('contact', models.JSONField(blank=True, default=dict, null=True)),
                ('bld_grp', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('dependents', models.JSONField(default=dict)),
                ('maritial_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20, null=True)),
                ('dom', models.DateField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('adaar_no', models.BigIntegerField(blank=True, null=True)),
                ('edu_qual', models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate'), ('Post Graduate', 'Post Graduate'), ('Others', 'Others')], max_length=20, null=True)),
                ('emerg_cont1', models.JSONField(default=dict)),
                ('emerg_cont2', models.JSONField(default=dict)),
                ('nominee_dtl', models.JSONField(default=dict)),
                ('bnk_name', models.CharField(blank=True, max_length=50, null=True)),
                ('brch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=10, null=True)),
                ('acc_no', models.BigIntegerField(blank=True, null=True)),
                ('acc_type', models.CharField(blank=True, max_length=20, null=True)),
                ('esi_appldt', models.DateField(blank=True, null=True)),
                ('esi_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pension_appli', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('esi_joindt', models.DateField(blank=True, null=True)),
                ('pf_appli', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('phy_hdcap', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('pf_cate', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Physical Handicapped', 'Physical Handicapped'), ('Handicapped Locomotive Disability', 'Handicapped Locomotive Disability'), ('Handicapped Visual', 'Handicapped Visual'), ('International Worker', 'International Worker')], max_length=50, null=True)),
                ('prev_pfno', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('pre_pfno', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_jod', models.DateField(blank=True, null=True)),
                ('uan', models.CharField(blank=True, max_length=20, null=True)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organisation.department')),
                ('desig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organisation.designation')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organisation.organisation_info')),
            ],
        ),
    ]
