# Generated by Django 4.0.3 on 2022-04-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organisation', '0002_department_created_at_department_status_and_more'),
        ('InTax', '0001_initial'),
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoSalsetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(blank=True, max_length=30, null=True)),
                ('cate', models.CharField(blank=True, choices=[('All', 'All'), ('Department', 'Department'), ('Designation', 'Designation'), ('Others', 'Others')], max_length=15, null=True)),
                ('sub_cate', models.CharField(blank=True, max_length=15, null=True)),
                ('esi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InTax.esi_ratecard')),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organisation.organisation_info')),
                ('pf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InTax.pf_empr')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySalsetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('co_salsetups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payroll.cosalsetup')),
                ('particulars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InTax.salary_heads')),
            ],
        ),
    ]
