# Generated by Django 4.0.3 on 2022-04-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
        ('Employee', '0002_alter_employee_info_doj'),
        ('Payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpMonthCtcMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.IntegerField(blank=True, null=True)),
                ('salary_head', models.JSONField(blank=True, default=dict, null=True)),
                ('emp_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee_info', unique=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
                ('temp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payroll.cosalsetup')),
            ],
        ),
        migrations.CreateModel(
            name='EmpMonPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=15, null=True)),
                ('salary_head', models.JSONField(blank=True, default=dict, null=True)),
                ('pf', models.FloatField(blank=True, null=True)),
                ('pt', models.FloatField(blank=True, null=True)),
                ('esi', models.FloatField(blank=True, null=True)),
                ('tds', models.FloatField(blank=True, null=True)),
                ('pf_empr', models.FloatField(blank=True, null=True)),
                ('esi_empr', models.FloatField(blank=True, null=True)),
                ('gross_salary', models.FloatField(blank=True, null=True)),
                ('net_salary', models.FloatField(blank=True, null=True)),
                ('tax_income', models.JSONField(blank=True, default=dict, null=True)),
                ('non_tax_income', models.JSONField(blank=True, default=dict, null=True)),
                ('other_dedu', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.BooleanField(default=False)),
                ('emp_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee_info', unique=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
            ],
        ),
        migrations.CreateModel(
            name='EmpCtcMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.IntegerField(blank=True, null=True)),
                ('incr_date_1', models.DateField(blank=True, null=True)),
                ('incr_ctc_1', models.IntegerField(blank=True, null=True)),
                ('eff_date_1', models.DateField(blank=True, null=True)),
                ('incr_date_2', models.DateField(blank=True, null=True)),
                ('incr_ctc_2', models.IntegerField(blank=True, null=True)),
                ('eff_date_2', models.DateField(blank=True, null=True)),
                ('incr_date_3', models.DateField(blank=True, null=True)),
                ('incr_ctc_3', models.IntegerField(blank=True, null=True)),
                ('eff_date_3', models.DateField(blank=True, null=True)),
                ('incr_date_4', models.DateField(blank=True, null=True)),
                ('incr_ctc_4', models.IntegerField(blank=True, null=True)),
                ('eff_date_4', models.DateField(blank=True, null=True)),
                ('emp_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee_info', unique=True)),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
            ],
        ),
    ]
