# Generated by Django 4.0.3 on 2022-04-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0003_alter_empmonpayroll_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='empctcmaster',
            name='temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payroll.cosalsetup'),
        ),
    ]
