# Generated by Django 4.0.3 on 2022-04-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0009_alter_empmonthctcmaster_emp_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empctcmaster',
            old_name='ctc',
            new_name='actc',
        ),
    ]
