# Generated by Django 4.0.3 on 2022-04-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0010_rename_ctc_empctcmaster_actc'),
    ]

    operations = [
        migrations.AddField(
            model_name='empctcmaster',
            name='ctc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empctcmaster',
            name='eff_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
