# Generated by Django 4.0.3 on 2022-04-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0011_empctcmaster_ctc_empctcmaster_eff_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmonthctcmaster',
            name='month',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
