# Generated by Django 4.0.3 on 2022-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0012_empmonthctcmaster_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmonpayroll',
            name='LOP_leaves',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='empmonpayroll',
            name='Net_payable_days',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='empmonpayroll',
            name='working_days',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
