# Generated by Django 4.0.3 on 2022-04-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0013_empmonpayroll_lop_leaves_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empmonpayroll',
            old_name='working_days',
            new_name='Total_days',
        ),
    ]
