# Generated by Django 4.0.3 on 2022-04-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_info_doj'),
        ('Global', '0001_initial'),
        ('Organisation', '0003_holidays'),
        ('Payroll', '0014_rename_working_days_empmonpayroll_total_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template_name', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_estimated', models.JSONField(blank=True, default=dict, null=True)),
                ('estimated_status', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted')], max_length=20, null=True)),
                ('estimated_allowed', models.JSONField(blank=True, default=dict, null=True)),
                ('allowed_status', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted')], max_length=20, null=True)),
                ('emp_actual_amount', models.JSONField(blank=True, default=dict, null=True)),
                ('actual_amount_status', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted')], max_length=20, null=True)),
                ('actual_allowed', models.JSONField(blank=True, default=dict, null=True)),
                ('actual_allowed_status', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted')], max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee.employee_info')),
                ('fy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organisation.organisation_info')),
            ],
        ),
    ]
