# Generated by Django 4.0.3 on 2022-04-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0015_taxdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDeclarationAtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('tax_decl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payroll.taxdeclaration')),
            ],
        ),
    ]
