# Generated by Django 4.0.3 on 2022-04-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0016_taxdeclarationatt'),
    ]

    operations = [
        migrations.AddField(
            model_name='empctcmaster',
            name='salary_head',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
