# Generated by Django 4.0.3 on 2022-04-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
        ('Attendence', '0002_remove_leavepolicy_carry_forword_next_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavepolicy',
            name='Custom',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='Fac',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='Shop',
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='fy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.financial_year'),
        ),
    ]
