# Generated by Django 4.0.3 on 2022-04-15 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0003_remove_leavepolicy_custom_remove_leavepolicy_fac_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactoriesAct',
        ),
        migrations.DeleteModel(
            name='ShopEstablishment',
        ),
    ]
