# Generated by Django 4.0.3 on 2022-04-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0005_leavepolicy_carry_forword_next_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyleaves',
            old_name='emp_id',
            new_name='emp_code',
        ),
        migrations.RenameField(
            model_name='attendancereport',
            old_name='emp_id',
            new_name='emp_code',
        ),
        migrations.RenameField(
            model_name='employeeshifts',
            old_name='emp_id',
            new_name='emp_code',
        ),
        migrations.RenameField(
            model_name='leavetable',
            old_name='emp_id',
            new_name='emp_code',
        ),
        migrations.RenameField(
            model_name='swipedata',
            old_name='emp_id',
            new_name='emp_code',
        ),
    ]
